# Generated by Django 4.0.3 on 2022-04-08 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_trip_description_alter_trip_left_places_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
