# Generated by Django 4.0.3 on 2022-04-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_trip_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatar.svg', null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='active',
            field=models.BooleanField(default='True'),
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('album', models.ManyToManyField(blank=True, related_name='album', to='base.image')),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.trip')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
