# Generated by Django 4.0.3 on 2022-04-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('adherent', 'ADHERENT'), ('non adherent', 'NON ADHERENT')], default='non adherent', max_length=14),
        ),
    ]
