# Generated by Django 4.0.3 on 2022-04-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_notification_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='name',
            field=models.CharField(choices=[('success', 'SUCCESS'), ('error', 'ERRORR')], max_length=10),
        ),
    ]
