# Generated by Django 4.0.3 on 2022-04-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_notification_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
