# Generated by Django 4.0.3 on 2022-04-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_notification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated',
        ),
    ]
