# Generated by Django 4.0.3 on 2022-04-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_notification_options_notification_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated',
        ),
    ]
