# Generated by Django 4.0.3 on 2022-04-21 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default='False'),
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_users', models.ManyToManyField(blank=True, related_name='banned_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
