# Generated by Django 4.0.3 on 2022-04-29 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_user_is_admin_user_is_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='album',
        ),
        migrations.AddField(
            model_name='image',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.blog'),
        ),
    ]
