# Generated by Django 4.0.3 on 2022-04-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_blog_album_image_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='taken_palces',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
