# Generated by Django 4.0.3 on 2022-04-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_trip_taken_palces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='taken_palces',
            new_name='taken_places',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='total_palces',
            new_name='total_places',
        ),
    ]
