# Generated by Django 4.0.3 on 2022-04-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_trip_depart_alter_trip_retour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='left_places',
            field=models.IntegerField(blank=True, default=models.IntegerField(blank=True, null=True), null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='taken_places',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
