# Generated by Django 4.0.3 on 2022-05-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_remove_blog_body_remove_blog_trip_blog_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triptype',
            name='code',
            field=models.CharField(default='h', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Simple', 'SIMPLE'), ('Adherant', 'ADHERENT'), ('Fidele', 'FIDELE')], default='non adherent', max_length=14),
        ),
    ]
