# Generated by Django 4.0.3 on 2022-05-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='bestfeedBody',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='bestfeedRate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='bestfeedUser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
