# Generated by Django 4.0.3 on 2022-05-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_user_phonenumber_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_left',
            field=models.BooleanField(blank=True, default='True', null=True),
        ),
    ]
