# Generated by Django 4.0.3 on 2022-05-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_closed',
            field=models.BooleanField(default='False'),
        ),
    ]
