# Generated by Django 4.0.3 on 2022-05-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_trip_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Simple', 'SIMPLE'), ('Adherant', 'ADHERENT'), ('Fidele', 'FIDELE')], default='Simple', max_length=14),
        ),
    ]
