# Generated by Django 4.0.3 on 2022-05-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_alter_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_banned',
        ),
        migrations.AddField(
            model_name='user',
            name='has_avatar',
            field=models.BooleanField(default='False'),
        ),
    ]
