# Generated by Django 4.0.3 on 2022-05-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_remove_user_is_banned_user_has_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_accepted',
            field=models.BooleanField(default='False'),
        ),
    ]
