# Generated by Django 4.0.3 on 2022-05-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_alter_notification_name_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='trip',
        ),
    ]
