# Generated by Django 4.0.3 on 2022-05-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_remove_feedback_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='bestfeedBody',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='bestfeedRate',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='bestfeedUser',
        ),
    ]
