# Generated by Django 4.0.3 on 2022-05-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_remove_trip_bestfeedbody_remove_trip_bestfeedrate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_left',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='section1',
        ),
        migrations.AddField(
            model_name='blog',
            name='main_section',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='section2_image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='section2_title',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='section3_image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='section3_title',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='section4_image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='section4_title',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='section5_image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='section5_title',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.DeleteModel(
            name='image',
        ),
    ]
