# Generated by Django 4.0.3 on 2022-05-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_remove_blog_blog_left_remove_blog_section1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='month_name',
            field=models.CharField(default='', max_length=12),
        ),
    ]
