# Generated by Django 4.0.3 on 2022-05-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_trip_month_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='blog_link',
            field=models.URLField(blank=True, db_index=True, max_length=300, null=True),
        ),
    ]
